#!/usr/bin/env python3
"""Writes the two single-file variants (local headers pasted in) that fit one Compiler Explorer pane.
usage: python3 make_single_files.py     writes tests_single_file.cpp and entt_single_file.cpp here.
The multi-translation-unit demo (tu_a.cpp, tu_b.cpp, runner.cpp) has no single-file form."""
import os, re
HERE = os.path.dirname(os.path.abspath(__file__))

def inline(name, seen):
    if name in seen:
        return ""
    seen.add(name)
    out = []
    for line in open(os.path.join(HERE, name)):
        m = re.match(r'#include "(.+)"', line)
        if m:
            out.append(inline(m.group(1), seen))
        elif not line.startswith("#pragma once"):
            out.append(line)
    return "".join(out)

for src, dst, note in [
    ("tests_one_tu.cpp", "tests_single_file.cpp", "no library needed"),
    ("entt_equal.cpp", "entt_single_file.cpp", "needs EnTT 4.x on the include path (Compiler Explorer library entt, version trunk)"),
]:
    text = f"// Single-file variant of {src} ({note}). Generated by make_single_files.py.\n" + inline(src, set())
    open(os.path.join(HERE, dst), "w").write(text)
